services:
    mysql_server:
        image: mysql
        container_name: mysql_server
        restart: always
        volumes:
            - ./database:/var/lib/mysql
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: final_db
            MYSQL_USER: final_user
            MYSQL_PASSWORD: f1234
        ports:
            - '3306:3306'
