version: '3.8'

services:
    mysql_server:
        image: mysql
        container_name: mysql_server
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: final_db
            MYSQL_USER: f1234
            MYSQL_PASSWORD: 
        ports:
            - '3306:3306'